services:
  django-web:
    build: .
    container_name: django-web
    command: ["sh", "./entrypoint.sh"]
    ports: 
    - "8000:8000"
    volumes:
	- .:/app
	- static_volume:/app/staticfiles

  volumes:
    static_volume:
